language: php
php:
  - '7.2'
  - '7.3'
  - '7.4'
  - 'nightly'

allow_failures:
  - php: nightly

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpstan analyse src --level=max
